name: Docker Build and Push

on:
  push:
    branches:
      - principal

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e enviar imagem
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: diegopm120/projeto-php-docker:latest
